#[package]
#name = "aoc2023"
#version = "1.0.0"
#authors = ["Jan-Lukas Wynen"]
#description = "Advent of code solution for 2023."
#license = "MIT"
#
#edition = "2021"
#rust-version = "1.73"
#
#include = ["src/input"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[dependencies]

[workspace]
members = ["aoc2023", "aoc2023-macro", "s01"]
resolver = "2"

#[[lib]]
#name = "aoc2023"
#path = "lib/aoc2023.rs"
#
#[[lib]]
#name = "aoc2023-macro"
#path = "aoc2023-macro/aoc2023-macro.rs"
#
#[[bin]]
#name = "01"
#path = "src01/main.rs"
