name:                s12
version:             2022
github:              "jl-wynen/advent-of-code"
license:             MIT
author:              "Jan-Lukas Wynen"
maintainer:          "j-l.wynen@hotmail.de"
copyright:           "2022 Jan-Lukas Wynen"
description:         Solution for advent of code 2022 day 12

data-files: input

dependencies:
- array == 0.5.4.0
- base >= 4.7 && < 5
- search-algorithms == 0.3.2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  s12:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
